/**
 * manu2print — Full Diagnostic Report PDF Generator
 *
 * Generates a structured, multi-page PDF report from StoredManuscript data
 * using pdf-lib (no headless browser required — runs in Vercel serverless).
 *
 * Output stored in R2 at uploads/{downloadId}/full-report.pdf
 */

import { PDFDocument, rgb, StandardFonts, PDFFont, PDFPage } from "pdf-lib";
import { getStored, updateMeta } from "@/lib/storage";
import { uploadFile, getSignedDownloadUrl } from "@/lib/r2Storage";
import type { StoredManuscript } from "@/lib/storage";

// ── Page dimensions (A4) ──────────────────────────────────────────────────────

const PW     = 595;   // page width pt
const PH     = 842;   // page height pt
const ML     = 36;    // margin left
const MR     = 36;    // margin right
const MT     = 36;    // margin top (below header)
const MB     = 36;    // margin bottom (above footer)
const CW     = PW - ML - MR; // content width = 523

// ── Color palette ─────────────────────────────────────────────────────────────

const C = {
  fail:    rgb(0.72, 0.12, 0.12),
  warn:    rgb(0.75, 0.48, 0.06),
  pass:    rgb(0.18, 0.55, 0.22),
  brand:   rgb(0.941, 0.353, 0.157),  // #F05A28
  green:   rgb(0.298, 0.851, 0.392),  // #4cd964
  dark:    rgb(0.102, 0.071, 0.031),  // #1A1208
  text:    rgb(0.13, 0.10, 0.04),
  muted:   rgb(0.42, 0.38, 0.30),
  border:  rgb(0.78, 0.73, 0.63),
  bg:      rgb(0.98, 0.97, 0.94),
  rowHead: rgb(0.20, 0.14, 0.05),
  white:   rgb(1, 1, 1),
} as const;

// ── Writer state ──────────────────────────────────────────────────────────────

interface Writer {
  doc:  PDFDocument;
  page: PDFPage;
  y:    number;   // current top of available space (decreasing as we add content)
  font: PDFFont;
  bold: PDFFont;
}

function addPage(w: Writer): void {
  w.page = w.doc.addPage([PW, PH]);
  w.y    = PH - MT;
}

/** Ensure at least `needed` pts remain on the current page; add new page if not. */
function ensureSpace(w: Writer, needed: number): void {
  if (w.y - needed < MB + 20) addPage(w);
}

// ── Text helpers ──────────────────────────────────────────────────────────────

function wrapText(text: string, font: PDFFont, size: number, maxW: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let cur = "";
  for (const word of words) {
    const candidate = cur ? `${cur} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxW) {
      cur = candidate;
    } else {
      if (cur) lines.push(cur);
      cur = word;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}

function fit(text: string, font: PDFFont, size: number, maxW: number): string {
  if (font.widthOfTextAtSize(text, size) <= maxW) return text;
  let t = text;
  while (t.length > 1 && font.widthOfTextAtSize(`${t}...`, size) > maxW) {
    t = t.slice(0, -1);
  }
  return `${t}...`;
}

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  size: number,
  font: PDFFont,
  color: ReturnType<typeof rgb> = C.text,
  opacity = 1,
): void {
  if (!text) return;
  page.drawText(text, { x, y, size, font, color, opacity });
}

// ── Per-page header (all pages) ───────────────────────────────────────────────

function drawPageHeader(page: PDFPage, filename: string, date: string, bold: PDFFont, font: PDFFont): void {
  // Dark strip
  page.drawRectangle({ x: 0, y: PH - 30, width: PW, height: 30, color: C.dark });

  // Brand wordmark
  page.drawText("manu", { x: ML, y: PH - 20, size: 12, font: bold, color: C.brand });
  const manuW = bold.widthOfTextAtSize("manu", 12);
  page.drawText("2print", { x: ML + manuW, y: PH - 20, size: 12, font: bold, color: C.green });

  // Center label
  const label = "KDP Compliance Report";
  const labelW = font.widthOfTextAtSize(label, 7);
  drawText(page, label, (PW - labelW) / 2, PH - 19, 7, font, rgb(0.7, 0.7, 0.7));

  // Right: date and filename
  const meta = `${date}  |  ${fit(filename, font, 6.5, 160)}`;
  const metaW = font.widthOfTextAtSize(meta, 6.5);
  drawText(page, meta, PW - MR - metaW, PH - 19, 6.5, font, rgb(0.55, 0.55, 0.55));
}

// ── Footer (all pages) ────────────────────────────────────────────────────────

function drawPageFooter(page: PDFPage, pageNum: number, font: PDFFont): void {
  page.drawLine({ start: { x: ML, y: 26 }, end: { x: PW - MR, y: 26 }, color: C.border, thickness: 0.3 });
  drawText(page, "Generated by manu2print.com — KDP PDF Checker", ML, 14, 6, font, C.muted);
  const pg = `${pageNum}`;
  const pgW = font.widthOfTextAtSize(pg, 6);
  drawText(page, pg, PW - MR - pgW, 14, 6, font, C.muted);
}

// ── Status banner ─────────────────────────────────────────────────────────────

function drawStatusBanner(w: Writer, grade: string, label: string, score: number): void {
  const bannerH = 36;
  ensureSpace(w, bannerH + 8);
  const { page } = w;

  const bannerCol = score >= 85 ? C.pass : score >= 50 ? C.warn : C.fail;

  page.drawRectangle({ x: ML, y: w.y - bannerH, width: CW, height: bannerH, color: bannerCol });

  // Grade circle
  page.drawEllipse({ x: ML + 22, y: w.y - bannerH / 2, xScale: 14, yScale: 14, color: C.white, opacity: 0.18 });
  const gW = w.bold.widthOfTextAtSize(grade, 11);
  drawText(page, grade, ML + 22 - gW / 2, w.y - bannerH / 2 - 4, 11, w.bold, C.white);

  // Label
  drawText(page, label, ML + 44, w.y - 15, 10, w.bold, C.white);
  // Desc line
  const desc = score >= 85 ? "Ready for upload" : score >= 50 ? "Needs fixes before uploading" : "Will be rejected by KDP";
  drawText(page, desc, ML + 44, w.y - bannerH + 9, 7.5, w.font, C.white, 0.85);

  // Score right
  const scoreStr = `${score}/100`;
  const scoreW = w.bold.widthOfTextAtSize(scoreStr, 18);
  drawText(page, scoreStr, ML + CW - scoreW - 10, w.y - bannerH / 2 - 6, 18, w.bold, C.white, 0.90);

  w.y -= bannerH + 10;
}

// ── Section header ────────────────────────────────────────────────────────────

function drawSectionHeader(w: Writer, title: string): void {
  ensureSpace(w, 24);
  const { page } = w;
  page.drawRectangle({ x: ML, y: w.y - 18, width: CW, height: 18, color: C.dark });
  drawText(page, title.toUpperCase(), ML + 8, w.y - 13, 7, w.bold, C.white, 0.90);
  w.y -= 18 + 4;
}

// ── Summary table row ─────────────────────────────────────────────────────────

const LABEL_COL_W = 140;

function drawSummaryRow(
  w: Writer,
  label: string,
  value: string,
  valueColor?: ReturnType<typeof rgb>,
): void {
  const rowH = 18;
  ensureSpace(w, rowH);
  const { page } = w;

  page.drawRectangle({ x: ML, y: w.y - rowH, width: CW, height: rowH, color: C.bg, borderColor: C.border, borderWidth: 0.3 });
  page.drawRectangle({ x: ML, y: w.y - rowH, width: LABEL_COL_W, height: rowH, color: C.rowHead });

  const lW = w.bold.widthOfTextAtSize(label, 6);
  drawText(page, label, ML + (LABEL_COL_W - lW) / 2, w.y - rowH + 6, 6, w.bold, C.white);
  drawText(page, fit(value, w.font, 8, CW - LABEL_COL_W - 16), ML + LABEL_COL_W + 8, w.y - rowH + 5, 8, w.font, valueColor ?? C.text);

  w.y -= rowH;
}

// ── Checklist row ─────────────────────────────────────────────────────────────

let _checkRow = 0;
function resetCheckRow(): void { _checkRow = 0; }

function drawCheckItem(w: Writer, label: string, status: "pass" | "warning" | "fail"): void {
  const rowH = 16;
  ensureSpace(w, rowH);
  const { page } = w;

  const bg = _checkRow++ % 2 === 0 ? C.bg : C.white;
  const statusCol = status === "pass" ? C.pass : status === "warning" ? C.warn : C.fail;
  const statusText = status === "pass" ? "PASS" : status === "warning" ? "WARN" : "FAIL";

  page.drawRectangle({ x: ML, y: w.y - rowH, width: CW, height: rowH, color: bg, borderColor: C.border, borderWidth: 0.2 });
  page.drawEllipse({ x: ML + 8, y: w.y - rowH / 2, xScale: 3.5, yScale: 3.5, color: statusCol });
  drawText(page, fit(label, w.font, 7.5, CW - 70), ML + 18, w.y - rowH + 5, 7.5, w.font, C.text);

  const stW = w.bold.widthOfTextAtSize(statusText, 7);
  drawText(page, statusText, ML + CW - stW - 6, w.y - rowH + 5, 7, w.bold, statusCol);

  w.y -= rowH;
}

// ── Spec table row ────────────────────────────────────────────────────────────

const SPEC_COL1 = Math.floor(CW * 0.34);
const SPEC_COL2 = Math.floor(CW * 0.26);
const SPEC_COL3 = Math.floor(CW * 0.28);
const SPEC_COL4 = CW - SPEC_COL1 - SPEC_COL2 - SPEC_COL3;

function drawSpecRow(
  w: Writer,
  req: string,
  yours: string,
  kdp: string,
  status: "pass" | "warning" | "fail",
  isHeader = false,
): void {
  const rowH = 18;
  ensureSpace(w, rowH);
  const { page } = w;

  const bg   = isHeader ? C.rowHead : C.bg;
  const fc   = isHeader ? C.white   : C.text;
  const font = isHeader ? w.bold    : w.font;
  const size = 7;

  page.drawRectangle({ x: ML, y: w.y - rowH, width: CW, height: rowH, color: bg, borderColor: C.border, borderWidth: 0.2 });

  drawText(page, fit(req,   font, size, SPEC_COL1 - 8), ML + 4,                              w.y - rowH + 6, size, font, fc);
  drawText(page, fit(yours, font, size, SPEC_COL2 - 8), ML + SPEC_COL1 + 4,                   w.y - rowH + 6, size, font, fc);
  drawText(page, fit(kdp,   font, size, SPEC_COL3 - 8), ML + SPEC_COL1 + SPEC_COL2 + 4,       w.y - rowH + 6, size, font, fc);

  if (isHeader) {
    const shW = w.bold.widthOfTextAtSize("STATUS", size);
    drawText(page, "STATUS", ML + SPEC_COL1 + SPEC_COL2 + SPEC_COL3 + (SPEC_COL4 - shW) / 2, w.y - rowH + 6, size, w.bold, C.white);
  } else {
    const statusCol  = status === "pass" ? C.pass : status === "warning" ? C.warn : C.fail;
    const statusText = status === "pass" ? "PASS" : status === "warning" ? "WARN" : "FAIL";
    const stW        = w.bold.widthOfTextAtSize(statusText, 7);
    drawText(page, statusText, ML + SPEC_COL1 + SPEC_COL2 + SPEC_COL3 + (SPEC_COL4 - stW) / 2, w.y - rowH + 6, 7, w.bold, statusCol);
  }

  w.y -= rowH;
}

// ── Issue item ────────────────────────────────────────────────────────────────

function drawIssueItem(
  w: Writer,
  msg: string,
  severity: string,
  page_num?: number,
  num?: number,
): void {
  const sev = severity.toLowerCase();
  const sevCol = (sev === "fail" || sev === "blocker" || sev === "error" || sev === "critical")
    ? C.fail : C.warn;

  const lines  = wrapText(msg, w.font, 7.5, CW - 28);
  const rowH   = lines.length * 10 + 8;

  ensureSpace(w, rowH + 4);
  const { page } = w;

  // Left accent bar
  page.drawRectangle({ x: ML, y: w.y - rowH, width: 3, height: rowH, color: sevCol });

  // Issue number
  if (num != null) {
    const nStr = String(num);
    const nW   = w.bold.widthOfTextAtSize(nStr, 7);
    drawText(page, nStr, ML + 6 + (6 - nW / 2), w.y - rowH / 2 - 3, 7, w.bold, sevCol);
  }

  // Issue text lines
  lines.forEach((line, i) => {
    drawText(page, line, ML + 18, w.y - 10 - i * 10, 7.5, w.font, C.text);
  });

  // Page number right
  if (page_num != null) {
    const pgStr = `p.${page_num}`;
    const pgW   = w.font.widthOfTextAtSize(pgStr, 6.5);
    drawText(page, pgStr, ML + CW - pgW, w.y - 10, 6.5, w.font, C.muted);
  }

  w.y -= rowH + 4;
}

// ── Main export: generate PDF from stored metadata ────────────────────────────

export async function generateReportPdf(meta: StoredManuscript): Promise<Buffer> {
  const report = meta.processingReport;
  if (!report) throw new Error("[generateReportPdf] No processing report on metadata");

  const doc  = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  // ── Data extraction ──────────────────────────────────────────────────────

  const filename = meta.originalName || "Unknown file";
  const scanDate = report.scanDate
    ? new Date(report.scanDate).toLocaleDateString("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" })
    : new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" });

  const grade      = report.scoreGrade?.grade ?? "-";
  const gradeLabel = report.scoreGrade?.label ?? "Unknown";
  const gradeDesc  = report.scoreGrade?.description ?? "";
  const score      = report.readinessScore100 ?? 0;
  const kdpProb    = Math.round((report.kdpPassProbability ?? 0) * 100);
  const riskLevel  = report.riskLevel ?? "Unknown";
  const pageCount  = report.pageCount ?? meta.pageCount ?? 0;
  const trimDet    = report.trimDetected ?? report.trimSize ?? "Unknown";
  const fileSizeMB = report.fileSizeMB ?? 0;
  const highRisk   = report.highRiskPageNumbers ?? [];
  const checklist  = report.uploadChecklist ?? [];
  const specTable  = report.specTable ?? [];
  const issues     = report.issuesEnriched ?? [];
  const recs       = report.recommendations ?? [];

  const failCount = issues.filter(i =>
    ["blocker", "fail", "error", "critical"].includes((i.severity ?? "").toLowerCase())
  ).length;
  const warnCount = issues.filter(i =>
    ["warning", "warn"].includes((i.severity ?? "").toLowerCase())
  ).length;

  const contextStr = `${trimDet}  |  ${pageCount} pages  |  ${fileSizeMB} MB`;
  const verdictStr = report.kdpReady ? "Ready for upload" : "Needs fixes before upload";
  const issueStr   = `Blockers ${failCount}  ·  Warnings ${warnCount}`;
  const riskStr    = `${kdpProb}% approval likelihood  ·  Risk: ${riskLevel}`;
  const issueColor = failCount > 0 ? C.fail : warnCount > 0 ? C.warn : C.pass;
  const riskColor  = kdpProb < 50 ? C.fail : kdpProb < 80 ? C.warn : C.pass;

  // ── Page 1 ───────────────────────────────────────────────────────────────

  const w: Writer = { doc, page: doc.addPage([PW, PH]), y: PH - MT, font, bold };

  drawPageHeader(w.page, filename, scanDate, bold, font);
  w.y = PH - 30 - 14; // below header strip + gap

  drawStatusBanner(w, grade, gradeLabel, score);

  // Grade description
  if (gradeDesc) {
    const descLines = wrapText(gradeDesc, font, 8, CW);
    for (const line of descLines) {
      ensureSpace(w, 12);
      drawText(w.page, line, ML, w.y, 8, font, C.muted);
      w.y -= 12;
    }
    w.y -= 4;
  }

  // Summary table
  drawSummaryRow(w, "SCAN CONTEXT",        contextStr);
  drawSummaryRow(w, "READINESS SCORE",     `${score} / 100`);
  drawSummaryRow(w, "VERDICT",             verdictStr, report.kdpReady ? C.pass : C.fail);
  drawSummaryRow(w, "ISSUE COUNTS",        issueStr,   issueColor);
  drawSummaryRow(w, "APPROVAL & RISK",     riskStr,    riskColor);
  w.y -= 10;

  // High-risk pages
  if (highRisk.length > 0) {
    ensureSpace(w, 14);
    drawText(w.page, `Pages most likely to cause print problems: ${highRisk.join(", ")}`, ML, w.y, 7.5, font, C.fail);
    w.y -= 14;
  }

  // Recommendations
  for (const rec of recs) {
    const lines = wrapText(rec, font, 7.5, CW);
    for (const line of lines) {
      ensureSpace(w, 12);
      drawText(w.page, line, ML, w.y, 7.5, font, C.muted);
      w.y -= 11;
    }
  }
  w.y -= 6;

  // Upload checklist
  if (checklist.length > 0) {
    drawSectionHeader(w, "Upload Readiness Checklist");
    resetCheckRow();
    for (const item of checklist) {
      drawCheckItem(w, item.check, item.status);
    }
    w.y -= 10;
  }

  // KDP spec comparison table
  if (specTable.length > 0) {
    drawSectionHeader(w, "KDP Spec Comparison");
    drawSpecRow(w, "Requirement", "Your File", "KDP Required", "pass", true);
    for (const row of specTable) {
      drawSpecRow(w, row.requirement, row.yourFile, row.kdpRequired, row.status);
    }
    w.y -= 10;
  }

  // Issues list
  if (issues.length > 0) {
    drawSectionHeader(w, `Issues Found (${issues.length})`);
    issues.forEach((issue, idx) => {
      drawIssueItem(
        w,
        issue.humanMessage || issue.originalMessage || "Issue detected",
        issue.severity ?? "warning",
        issue.page ?? undefined,
        idx + 1,
      );
    });
  }

  // ── Footers on all pages ──────────────────────────────────────────────────

  const pages = doc.getPages();
  pages.forEach((p, i) => {
    // Re-draw header on pages after page 1
    if (i > 0) drawPageHeader(p, filename, scanDate, bold, font);
    drawPageFooter(p, i + 1, font);
  });

  const bytes = await doc.save({ useObjectStreams: false });
  return Buffer.from(bytes);
}

// ── Store to R2 and update metadata ──────────────────────────────────────────

const REPORT_FILENAME = "full-report.pdf";

export async function generateAndStoreReportPdf(
  downloadId: string,
): Promise<{ fullReportPdfDownloadUrl: string } | null> {
  try {
    const meta = await getStored(downloadId);
    if (!meta) return null;
    if (!meta.processingReport || meta.processingReport.outputType !== "checker") return null;

    // Return cached URL if already stored
    if (meta.fullReportPdfDownloadUrl) {
      return { fullReportPdfDownloadUrl: meta.fullReportPdfDownloadUrl };
    }

    const pdfBuffer = await generateReportPdf(meta);

    await uploadFile(downloadId, REPORT_FILENAME, pdfBuffer);
    const fullReportPdfDownloadUrl = await getSignedDownloadUrl(downloadId, REPORT_FILENAME);

    await updateMeta(downloadId, { fullReportPdfDownloadUrl });

    return { fullReportPdfDownloadUrl };
  } catch (err) {
    console.error("[generateReportPdf] generateAndStoreReportPdf failed:", err);
    return null;
  }
}
